Repository wisemen-digital/flutter-core, pull requests merged in 2024-04, with the labels that each got.

#1 Formatted and updated package
  CHANGELOG.md
  lib/core/base_utils/base_utils.dart
  lib/core/error_dialog/error_dialog_helper.dart
  lib/core/extensions/list_extension.dart
  lib/core/extensions/scroll_extensions.dart
  lib/core/extensions/time_of_day_extension.dart
  lib/core/models/pagination_object/pagination_object.dart
  lib/core/platform_app/platform_app.dart
  lib/core/platform_app/platform_widget.dart
  lib/generated/s_core_localizations.dart
  lib/generated/s_core_localizations_de.dart
  lib/generated/s_core_localizations_en.dart
  lib/generated/s_core_localizations_es.dart
  lib/generated/s_core_localizations_fr.dart
  lib/generated/s_core_localizations_nl.dart
  lib/generated/s_core_localizations_ro.dart
  pubspec.yaml
Labels: 📃 S PR

#2 Release 1.0.6
  CHANGELOG.md
  pubspec.yaml
Labels: 📃 XS PR

#4 updated all packages in pubspec.yaml
  lib/generated/s_core_localizations.dart
  lib/generated/s_core_localizations_de.dart
  lib/generated/s_core_localizations_en.dart
  lib/generated/s_core_localizations_es.dart
  lib/generated/s_core_localizations_fr.dart
  lib/generated/s_core_localizations_nl.dart
  lib/generated/s_core_localizations_ro.dart
  pubspec.yaml
Labels: 📃 S PR, ✨ feature

#5 Organized imports
  CHANGELOG.md
  lib/core/core.dart
  lib/core/platform_app/platform_app.dart
  lib/core/router/app_router.dart
  lib/core/services/shared_preferences.dart
  pubspec.yaml
Labels: 📃 XS PR

#6 Improved showErrorDialog extension on AsyncValue
  CHANGELOG.md
  lib/core/error_dialog/error_dialog_helper.dart
  pubspec.yaml
Labels: 📃 XS PR
